#!/bin/bash

usage() { echo "Usage: $0 [-c] [machine]" 1>&2; exit 1; }

compiled=false

while getopts ":c" o; do
    case "${o}" in
        c)
            javac edu/harvard/cs262/ComputeServer/SimpleServer/*.java
            javac tasks/*.java
            jar cvf compute.jar edu/harvard/cs262/ComputeServer/*.class tasks/*.class
            javac -cp compute.jar edu/harvard/cs262/ComputeServer/SimpleServer/Server.java
            javac -cp compute.jar edu/harvard/cs262/ComputeServer/SimpleServer/Client.java
            javac -cp compute.jar workerServer/QueuedServer.java
            compiled=true
            ;;
        \?)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ "$1" == client ]; then
    if [ "$compiled" = false ]; then
        javac -cp compute.jar edu/harvard/cs262/ComputeServer/SimpleServer/Client.java
    fi

    java edu/harvard/cs262/ComputeServer/SimpleServer/Client rinchiera.com

elif [ "$1" == server ]; then
    if [ "$compiled" = false ]; then
        javac -cp compute.jar edu/harvard/cs262/ComputeServer/SimpleServer/Server.java
    fi

    java -Djava.rmi.server.hostname=rinchiera.com edu/harvard/cs262/ComputeServer/SimpleServer/Server

elif [ "$1" == queue ]; then
    if [ "$compiled" = false ]; then
        javac -cp compute.jar workerServer/QueuedServer.java
    fi

    java -Djava.rmi.server.hostname=rinchiera.com workerServer/QueuedServer

fi
