#!/bin/bash

javac edu/harvard/cs262/ComputeServer/SimpleServer/*.java
javac tasks/*.java
jar cvf compute.jar edu/harvard/cs262/ComputeServer/*.class tasks/*.class
javac -cp compute.jar edu/harvard/cs262/ComputeServer/SimpleServer/Server.java
javac -cp compute.jar edu/harvard/cs262/ComputeServer/SimpleServer/Client.java

java edu/harvard/cs262/ComputeServer/SimpleServer/Client rinchiera.com
